name: Sourdough Monitor
url: https://github.com/jwiemann/doughmonitor
version: "0.1.23"
slug: sourdough_monitor
description: Monitor sourdough rise from Frigate camera snapshots with MQTT discovery
arch:
  - aarch64
  - amd64
init: false
startup: application
boot: auto
homeassistant_api: true
services:
  - mqtt:need
options:
  frigate_camera: "battery_cam"
  frigate_sample_interval_minutes: 10
  mqtt_device_id: "sourdough_monitor"
  debug_enabled: false
schema:
  frigate_camera: str
  frigate_sample_interval_minutes: int(1,60)
  mqtt_device_id: str
  debug_enabled: bool
